### ISSUE TITLE
GTA_sa.exe crashes when exit game

### ISSUE THREAD

**Issue by Gustingorriz** [thelink2012/modloader#23]
First of all, THANK YOU Link for modloader, It can be easily the best mod ever made for GTA SA apart from SAMP/MTA. I'm modding GTA SA since 2009 and its hard to believe how can mods like this can give San Andreas years and years of joyness.

But unfortunately my modloader isnt running smoothly; it keeps crashing when I close the game. I've replaced peds, cars and some effects, which looks perfect in game. I know is stupid because the game itself goes well, but is very annoying get the "gta_sa.exe stopped working" when close the game.

Have you any idea how to solve this? Here's my log file:
https://www.dropbox.com/s/dj3xf7ufenfeyh5/modloader.log?dl=0

Lot of thanks.

**Comment by thelink2012** [comment]
Hey, thanks for you feedback.

Does not seem like a issue directly related to Mod Loader but let's make sure.
* Take modloader.asi out of your game dir, essentially completly disabling Mod Loader.
* Still crashes when you get out of the game? If it doesn't go ahead, otherwise caused by something else.
* Restore modloader.asi and set _IgnoreAllFiles_ to _true_ in _modloader/modloader.ini_
* Still crashes when you get out of the game? If it doesn't must be caused by one of the mods installed in Mod Loader, you could find out which one by adding them to the _IgnoreMods_ section of the ini until you find which one (or just move the mod dir out of modloader)
* Set _IgnoreAllFiles_ back to _false_ of course =P

So what do we have?

**Comment by Gustingorriz** [comment]
thanks for your quick response Link! As far I know:

1-If I delete all modloader data from the directory, game runs ok
2-If I set IgnoreMods to true, game runs ok
3-So must be one of the mods installed, which is strange because I only have txd/dff files placed on it (and a file with .fxp extension)
Any suggestion at this point? I will search which mod or mod folder is causing the crash

Thanks again!

**Comment by thelink2012** [comment]
No problem. When you find which one is causing the issue let me know and send it to me :+1:

**Comment by Gustingorriz** [comment]
Seems fixed :)

You was right; some of my weapon mods was causing the error, I dont know why because it looked good in-game! Anyway I've replaced all the weapons with new models and, for now, no crashes :+1: 

Thanks you for the help, I was getting out of ideas!
