### ISSUE TITLE
Support GTA3 1.1

### ISSUE THREAD

**Issue by jamierocks** [thelink2012/modloader#68]
Its rather unfortunate that modloader doesn't support 1.1. Seems most other mods support it.

EDIT: Looks like it only requires a translator be written, can't seem to find any documented memory locations online, any tips on obtaining them?

**Comment by thelink2012** [comment]
Relates to #8 

>EDIT: Looks like it only requires a translator be written, can't seem to find any documented memory locations online, any tips on obtaining them?

Usually you need to disassembly (or find a idb database) of the 1.1 version, and try fiding the corresponding addresses. I think the address difference between 1.0 and 1.1 are very minimal, at very specific parts, and an translator could very much be just a pos-processor on the 1.0 addresses.

@ThirteenAG any ideas?

**Comment by ThirteenAG** [comment]
I only have maxorator's python script to convert 1.0 addresses of VC in source code files to 1.1 addresses.
Personally I don't see a point in III's 1.1 exe. It's only popular because fan translations made for 1.1 have messed up spacing and whatnot if used with 1.0 exe. Which is easily fixable with a small plugin, but I guess no one bothered.
And I wouldn't say most mods support 1.1. Most mods I encountered support either 1.0 or both.

**Comment by ghost** [comment]
is there any workaround?????

**Comment by thelink2012** [comment]
As #8 has been closed I'll close this too. Refer to ThirteenAG's comment for a reasoning. Use a 1.0 EXE, that's the de-facto standard for modding.
